################################################
### HEALTH CHECK
################################################
GET http://localhost:5000
################################################
### REGISTER USER (ADMIN)
################################################
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "full_name": "Admin User21",
  "email": "admin@test21.com",
  "password": "12345678",
  "role": "admin"
}

################################################
### REGISTER NORMAL USER
################################################
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "full_name": "Customer2 User",
  "email": "user@test57.com",
  "password": "12345679",
  "role": "user"
}



################################################
### LOGIN (ADMIN)
################################################
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@test21.com",
  "password": "12345678"
}



################################################
### LOGIN (USER)
################################################
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "user@test57.com",
  "password": "12345679"
}

################################################
### CREATE CATEGORY (ADMIN TOKEN REQUIRED)
################################################
### CREATE CATEGORY (ADMIN TOKEN REQUIRED)
POST http://localhost:5000/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3Mjc4NTkxNiwiZXhwIjoxNzcyODcyMzE2fQ.Mi7V4vQ5Ap8b64q4n0mj4igNTcxvLK4_O07b3HUEhFY

{
  "name": "Sculpture"
}


################################################
### GET ALL CATEGORIES
################################################
GET http://localhost:5000/api/categories



################################################
### CREATE PRODUCT (ADMIN TOKEN REQUIRED)
################################################
POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3Mjc4NTkxNiwiZXhwIjoxNzcyODcyMzE2fQ.Mi7V4vQ5Ap8b64q4n0mj4igNTcxvLK4_O07b3HUEhFY

{
  "name": "Golden Horse Sculpture",
  "description": "Premium handcrafted sculpture",
  "price": 5000,
  "image_url": "https://example.com/horse.jpg",
  "category_id": 1,
  "is_featured": true
}



################################################
### GET ALL PRODUCTS (PAGINATION + FILTER)
################################################
GET http://localhost:5000/api/products?page=1&limit=5



################################################
### FILTER BY CATEGORY
################################################
GET http://localhost:5000/api/products?category=1



################################################
### FILTER BY PRICE RANGE
################################################
GET http://localhost:5000/api/products?minPrice=1000&maxPrice=6000



################################################
### SORT BY PRICE
################################################
GET http://localhost:5000/api/products?sort=price



################################################
### GET FEATURED PRODUCTS
################################################
GET http://localhost:5000/api/products/featured



################################################
### GET SINGLE PRODUCT
################################################
GET http://localhost:5000/api/products/1



################################################
### UPDATE PRODUCT (ADMIN TOKEN REQUIRED)
################################################
PUT http://localhost:5000/api/products/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3Mjc4NTkxNiwiZXhwIjoxNzcyODcyMzE2fQ.Mi7V4vQ5Ap8b64q4n0mj4igNTcxvLK4_O07b3HUEhFY
{
  "name": "Updated Sculpture",
  "description": "Updated description",
  "price": 6000,
  "image_url": "https://example.com/new.jpg",
  "category_id": 1,
  "is_featured": false
}



################################################
### DELETE PRODUCT (ADMIN TOKEN REQUIRED)
################################################
DELETE http://localhost:5000/api/products/1
Authorization: Bearer YOUR_ADMIN_TOKEN_HERE

